### ISSUE TITLE
[Suggestion] - secrets.json for sensitive data. 

### ISSUE THREAD

**Issue by taeo** [leemunroe/grunt-email-design#19]
In my exploration with this project, I created a `secrets.json` file and added it to `.gitignore` (example below). 

I feel it's good practice to get cloners off to a good start, discouraging them from commiting Gruntfiles with sensitive information. 

@leemunroe - I'm happy to fork and send a PR if this is something you're into.

__Gruntfile.js__
Using `<%= secrets.mailgun.api_key %>` in the `mailgun` task.

```js
grunt.initConfig({
        secrets: grunt.file.readJSON('secrets.json'),
});
```
__secrets.json__
```json
{
    "mailgun": {
        "api_key": "YOUR MG PRIVATE API KEY"
    },
    "litmus": {
        "username" : "LITMUS USER NAME",
        "password" : "LITMUS PASS"
    }
}
```

**Comment by leemunroe** [comment]
I think it's a great idea. Been trying to figure out a solution to this that I can use (push/pull) seamlessly and that new users can understand.
